stages:
  - publish

publish:
  image: node:latest
  stage: publish
  only:
  - tags
  artifacts:
    paths:
      - package.json
      - babel.config.js
      - dist/
      - source/
    expire_in: never

  script:
  - apt-get update && apt-get install -y jq
  - jq ".version = \"$CI_COMMIT_REF_NAME\"" package.json > package.tmp
  - mv -f package.tmp package.json
  - npm install
  - npm run build
