stages:
  - publish

publish:
  image: node:latest
  stage: publish
  only:
  - tags
  artifacts:
    paths:
      - module.tar.gz
    expire_in: never

  script:
  - apt-get update && apt-get install -y jq
  - jq ".version = \"$CI_COMMIT_REF_NAME\"" package.json > package.tmp
  - mv -f package.tmp package.json
  - npm install
  - npm run build
  - mkdir package
  - cp package.json package/
  - cp babel.config.json package/
  - cp -r dist package/
  - cp -r src package/
  - tar -czvf module.tar.gz package/
